client:
  container_name: 'foosbot.client'
  build: client
  command: ./foosbot
  links:
   - server

server:
  container_name: 'foosbot.server'
  build: server
  environment:
    DEBUG: '*'
  command: node index
  expose:
    - '80'
  ports:
    - '61445:80' # FOO5
